### ISSUE TITLE
Deposit mining metric

### ISSUE THREAD

**Issue by JonathanSafer** [jordansafer/screeps#58] opened 2019-12-30 01:40 UTC
amount of commodity mined should be recorded in stats to be used as a metric to measure profitability.

**Comment by JonathanSafer** [comment] 2019-12-30 01:47
On trip home, deposit miner can log quantity mined in global (On the same tick as the stats runs). Upon successful logging, dMiner flips a bool in memory to prevent it from logging again.\

In stats function, check if any logs have been made to the global. If they have, log the new quantity, else log 0. Make sure to delete the global variable so it does not get used again on the next iteration!

**Comment by jordansafer** [comment] 2019-12-30 19:05
Duplicate of #46 . Solution deployed

**Closed by jordansafer** 2019-12-30 19:05 UTC
Labels: Market, enhancement
